version: '3.8'
services:
  ms-eureka-service:
    image: ms-eureka-service:latest
    container_name: ms-eureka-service
    restart: always
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
    networks:
      - eureka-network

  ms-config-service:
    image: ms-config-service:latest
    container_name: ms-config-service
    restart: always
    ports:
      - "8888:8888"
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
    networks:
      - eureka-network

  ms-iam-service:
    image: ms-iam-service:latest
    container_name: ms-iam-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
      DB_URL: jdbc:mysql://db:3306/iamdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    ports:
      - "8094:8094"
    networks:
      - eureka-network

  ms-gateway-service:
    image: ms-gateway-service:latest
    container_name: ms-gateway-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      ms-eureka-service:
        condition: service_started
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
    networks:
      - eureka-network

  ms-profile-service:
    image: ms-profile-service:latest
    container_name: ms-profile-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
      DB_URL: jdbc:mysql://db:3306/profiledb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    ports:
      - "8096:8096"
    networks:
      - eureka-network

  ms-accommodation-service:
    image: ms-accommodation-service:latest
    container_name: ms-accommodation-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
      DB_URL: jdbc:mysql://db:3306/accommodationdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    ports:
      - "8741:8741"
    networks:
      - eureka-network

  ms-messages-service:
    image: ms-communications-service:latest
    container_name: ms-messages-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
      DB_URL: jdbc:mysql://db:3306/messagesdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    ports:
      - "8963:8963"
    networks:
      - eureka-network

  ms-employees-service:
    image: ms-employees-service:latest
    container_name: ms-employees-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
      DB_URL: jdbc:mysql://db:3306/employeesdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    ports:
      - "8463:8463"
    networks:
      - eureka-network

  ms-inventory-service:
    image: ms-inventory-service:latest
    container_name: ms-inventory-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
      DB_URL: jdbc:mysql://db:3306/inventorydb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    ports:
      - "8041:8041"
    networks:
      - eureka-network

  ms-tasks-service:
    image: ms-task-service:latest
    container_name: ms-tasks-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ms-config-service:
        condition: service_started
    environment:
      EUREKA_URL: http://ms-eureka-service:8761/eureka/
      CONFIG_SERVER_HOST: 'http://ms-config-service:8888'
      DB_URL: jdbc:mysql://db:3306/tasksdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    ports:
      - "8025:8025"
    networks:
      - eureka-network

  db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: iamdb
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge


