server:
  port: 8741

  servlet:
    context-path: /msvc-accommodation

spring:
  application:
    name: msvc-accommodation
  profiles:
    default: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/accommodationdb?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:12345678}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}