server:
  port: 8094

  servlet:
    context-path: /msvc-iam

spring:
  application:
    name: msvc-iam
  profiles:
    default: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/iamdb?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:12345678}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

authorization:
  jwt:
    secret: d1f4a5f8c3d555d31a9e07547cffe13bc174c6a70a54d37b9bddded4b9d1a86a
    expiration:
      days: 7