server:
  port: 8080

logging:
  file:
    name: app.log

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}