spring:
  application:
    name: msvc-gateway

  profiles:
    default: oauth2

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}