apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-config-service
  template:
    metadata:
      labels:
        app: ms-config-service
    spec:
      containers:
        - name: ms-config-service
          image: microserviceinncontrol.azurecr.io/ms-config-service:latest
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_URL
              value: "http://ms-eureka-service:8761/eureka/"

---
apiVersion: v1
kind: Service
metadata:
  name: ms-config-service
spec:
  type: ClusterIP
  selector:
    app: ms-config-service
  ports:
    - port: 8888
      targetPort: 8888
