apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-eureka-service
  template:
    metadata:
      labels:
        app: ms-eureka-service
    spec:
      containers:
        - name: ms-eureka-service
          image: microserviceinncontrol.azurecr.io/ms-eureka-service:v1.1
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVER_HOST
              value: "http://ms-config-service:8888"

---
apiVersion: v1
kind: Service
metadata:
  name: ms-eureka-service
spec:
  type: ClusterIP
  selector:
    app: ms-eureka-service
  ports:
    - port: 8761
      targetPort: 8761
