apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tasks-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-tasks-service
  template:
    metadata:
      labels:
        app: ms-tasks-service
    spec:
      containers:
        - name: ms-tasks-service
          image: microserviceinncontrol.azurecr.io/ms-task-service:latest
          ports:
            - containerPort: 8025
          env:
            - name: EUREKA_URL
              value: "http://ms-eureka-service:8761/eureka/"
            - name: CONFIG_SERVER_HOST
              value: "http://ms-config-service:8888"
            - name: DB_URL
              value: "jdbc:mysql://db:3306/tasksdb?createDatabaseIfNotExist=true&serverTimezone=UTC"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "1234"

---
apiVersion: v1
kind: Service
metadata:
  name: ms-tasks-service
spec:
  type: ClusterIP
  selector:
    app: ms-tasks-service
  ports:
    - port: 8025
      targetPort: 8025
