server :
  port : 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"


eureka:
  instance:
    hostname : localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/