server:
  port: 8761

spring:
  application:
    name: eureka-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
