server:
  port: 8888

spring:
  profiles:
    active : native
  application:
    name : config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}